---
title: TØ 7. Extra
pyodide:
  packages:
    - pandas
    - openpyxl
---

```{python}
import pandas as pd
pigments = pd.read_csv('../../datasets/curated_abs_dataset.csv')
display(pigments)
```

```{pyodide}
#| echo: false

import matplotlib.pyplot as plt
import pandas as pd

url = 'https://raw.githubusercontent.com/au-mbg/imol/refs/heads/main/course_notes/datasets/curated_abs_dataset.csv'

pigments = pd.read_csv(url)
```

## Data manipulations

We often need to transform parts of our data - e.g. 

- Converting units
- Calculating derived properties
- Normalizing 

Our dataset has the wavelength in nanometers, perhaps we would like to work with meters instead 

```{python}
pigments['wavelength_m'] = pigments['wavelength_nm'] * 10**(-9)
```

This is an example of an **element-wise operation** - every element of `pigments['wavelength_nm']`
is multiplied by `10**(-9)`. 

### Exercise: Converting to photon energy

A more interesting unit conversion for this dataset would be to work with photon energy in eV, 
which can be computed with the formula 

$$
E = \frac{1240}{\lambda}
$$
Where $E$ is the photon energy and $\lambda$ is the wavelength.

Use the cell below to make this conversion

```{pyodide}
#| exercise: convert_exercise
#| setup: true

import matplotlib.pyplot as plt
import pandas as pd

url = 'https://raw.githubusercontent.com/au-mbg/imol/refs/heads/main/course_notes/datasets/curated_abs_dataset.csv'

pigments = pd.read_csv(url)
```

```{pyodide}
#| exercise: convert_exercise
# Replace the blank line below with your code to make the conversion
_______

# Make a plot with the x-axis as photon energy 
fig, ax = plt.subplots()

_______ 

plt.show()
```

### Exercise: Mixture of pigments

```{pyodide}
#| exercise: mixture_exercise
#| setup: true  

import matplotlib.pyplot as plt
import pandas as pd

url = 'https://raw.githubusercontent.com/au-mbg/imol/refs/heads/main/course_notes/datasets/curated_abs_dataset.csv'

pigments = pd.read_csv(url)
```

We can approximate the absorbance of a mixture by using the equation 

$$
A_{\mathrm{mixture}}(\lambda) = c_1 \cdot A_1(\lambda) + c_2 \cdot A_2(\lambda)
$$
Where $A$ are absorbances of each component of the mixture and $c_i$ are proportions of each component. Use this to calculate the absorbance of a mixture of 70% `chlorophyll-a` and 30% `chlorophyll-b` 

```{pyodide}
#| exercise: mixture_exercise
# Calculate the mixture
c1 = ______
c2 = ______
A_mixture = _______

# Plot the mixture absorbance
fig, ax = plt.subplots()

x_data = pigments['wavelength_nm']
ax.plot(x_data, pigments['chlorophyll-a'], label='c-a')
ax.plot(x_data, pigments['chlorophyll-b'], label='c-b')
______

plt.show()
```


