---
title: Data types
format: 
  live-html:
    toc: true
    number-sections: true
    css: ../styling/styles.css
    theme:
      light: cosmo
      dark: [darkly, ../styling/theme-dark.scss]
    respect-user-color-scheme: true
---

One of the most useful aspects of Python is the ability to work with complex datasets. 
However, to do so it is useful to understand a little bit about **data types**. 

## The primary data types. 

We will consider three primary data types 

- **Integers** (*whole numbers*): Used to represent whole numbers, for example the number of bases or codons. 
- **Floats** (*decimal numbers*): Used to represent decimal numbers, for example a concentration in $\frac{\mathrm{ng}}{\mathrm{\mu L}}$.
- **Strings** (*text*): Used to represent text, for example mRNA-sequences or names. 

The code block below shows a variable of each of these types 

```{pyodide}
an_integer = 1
a_float = 3.1415
a_string = "Monkeybread"

print('Integer: ', an_integer, type(an_integer))
print('Float: ', a_float, type(a_float))
print('a_string: ', a_string, type(a_string))
```

::: {.callout-tip}
Here the function `type` was used to obtain the type that Python uses for each of our variables. 
You don't need to understand the details of this - just notice that these three pieces of data were automatically understood to be one of the above types. 
:::

### Exercise: mRNA and datatypes.

Consider working with an mRNA molecule with sequence `GCAUGCCGUUUGGAUGACCG`. 

### Sequence data type

What Python data type would it be natural to use for an mRNA sequence? 

### Sequence length 

What Python data type would it be natural to use for the length of an mRNA sequence? 

### In Python

Using the cell below, how many nucleotides are in the sequence? 

```{pyodide}
mrna = "GCAUGCCGUUUGGAUGACCG"
sequence_length = len(mrna)

print("The sequence has length:", sequence_length)
```

::: {.callout-tip}
The `len` function is incredibly useful - here we used it to return the number of characters in a string. 
:::

### mRNA codons 

Which data type would it be natural to use for the number of codons in the mRNA? 

```{pyodide}
mrna = "GCAUGCCGUUUGGAUGACCG"
sequence_length = len(mrna)

print("The sequence has length:", sequence_length)
```

## Data collections: Lists 

The three primary types we saw above can describe a lot of things, however an actual dataset is 
typically a collection of several measurements/labels/etc. Imagine for example an experiment where the absorption coefficent is measured as a function of wavelength, we could represent that 
as 

```python
wavelength_1 = 400
absorption_1 = 2.451
wavelength_2 = 401
absorption_2 = 2.532
...
```
However, its pretty clear that this becomes really annoying to deal with very quickly - so we need something smarter. The simplest collection is a list

```{python}
wavelengths = [400, 401, 402, 403, 404, 405]
absorptions = [2.451, 2.532, 2.567, 2.621, 2.584]
```
This is not too bad, it keeps the wavelengths grouped together and similarly for the absorptions. 

::: {.callout-note title="Using lists for plotting"}

Lists are also the type of input that is usually used for plotting, consider for example the cell below that makes a very basic plot. 

```{python}
#| fig-align: center
import matplotlib.pyplot as plt

x = [0, 1, 2, 3, 4]  # <1>
y = [0, 1, 4, 9, 16] # <2>

fig, ax = plt.subplots() # <3>

ax.plot(x, y, '-o') # <4>
```
1. Make a list of $x$-coordinates.
2. Make a list of $y$-coordinates.
3. Make the figure (fig) and axis (ax) for plotting
4. Plot the data in the axis.

This code produces the shown figure. You will learn much more about plotting through out your 
studies as it is an essential part of working with scientific data. 

:::

For plotting we use every entry in the lists, but there are many situations in which we 
want to select a specific element of a dataset - this is achieved through *indexing*. 

For example with the `wavelengths`-list we made before, we can index elements like so

```{python}
element_1 = wavelengths[0]
print("The first element is: ", element_1)
```

The indexing happened with the code `wavelengths[0]` where `[0]` specifies we want the first element. This may seem a little surprising, why do we use `[0]`? There is a simple reason for this, explained briefly in the footnote[^1].

### Exercise: Indexing a list of molecules 

In an experiemnt, several molecules were identified in a sample, use the cell below 
to

1. Print the first molecule
2. Print the third molecule
3. Print the last molecule


```{pyodide}
#| exercise: list_of_molecules
#| check: true

feedback = {"correct": False, "message": "..."}

if molecules[first_index] != molecules[0]:
    feedback["message"] = "first_index is incorrect..."
elif molecules[third_index] != molecules[2]:
    feedback["message"] = "second_index is incorrect..."
elif molecules[last_index] != molecules[-1]:
    feedback["message"] = "last_index is incorrect..."
else:
    feedback["correct"] = True
    feedback["message"] = "That's correct, good job!"

feedback 
```

```{pyodide}
#| exercise: list_of_molecules
molecules = ["glucose", "ATP", "cholesterol", "lactate", "glycine"]

first_index = ______
print("The first molecule is: ", molecules[first_index])

third_index = ______
print("The third molecule is: ", molecules[third_index])

last_index = ______
print("The last molecule is: ", molecules[last_index])
```

### Exercise: Building a sentence

The following list contains parts of a sentence in the wrong order.

Fill in the indices so that the printed sentence is correct.

```{pyodide}
#| exercise: powerhouse_of_the_cell
#| check: true

if first_index != 2 or second_index != 1 or third_index != 0 or fourth_index != 3: 
    feedback = {"correct": False, "message": "That doesn't seem quite right..."}
else:
    feedback = {"correct": True, "message": "Great job!"}

feedback
```


```{pyodide}
#| exercise: powerhouse_of_the_cell
sentence_pieces = [
    "powerhouse", 
    "are the", 
    "mitochondria",
    "of the cell"]

first_index = ______
second_index = ______
third_index = ______
fourth_index = ______


print(
    sentence_pieces[first_index], 
    sentence_pieces[second_index], 
    sentence_pieces[third_index], 
    sentence_pieces[fourth_index]
)
```

## Data collections: Revisiting strings

Earlier we introduced strings as a basic datatype, but in some ways they can actually 
also be considered a collection - and therefore strings can also be indexed. 

For example, we can print the fourth element of an mRNA sequence like shown below

```{python}
mrna = "GCAUGCCGUUUGGAUGACCG"
print(mrna[3])
```

This also lets us use another form of indexing a *slice*, for example 

```{python}
mrna = "GCAUGCCGUUUGGAUGACCG"
codon = mrna[0:3]
print(codon)
```

Here `[0:3]` means: start at index 0 and stop *before* index 3.

### Exercise: Find the third codon.

For the `mrna` sequence use a slice to print the third codon 

```{pyodide}
#| exercise: the-third-codon
#| check: true

if codon == "CGU": 
    feedback = {"correct": True, "message": "That's a nice codon."}
else:
    feedback = {"correct": False, "message": "That's not quite right."}

feedback
```


```{pyodide}
#| exercise: the-third-codon
mrna = "GCAUGCCGUUUGGAUGACCG"
codon = mrna[______]
print(codon)
```

## Data collections: Arrays

Another very common collection is an *array*. Arrays are typically used for numerical 
data as they make computations simple as they enable *element-wise calculations*. 
This means that we can perform the same calculation for every element in an array. 

Consider for example converting distances in kilometers to distances in meters. 

```{python}
import numpy as np

distance_in_km = np.array([1.43, 75.12, 9.042, 1.337])
distance_in_m = distance_in_km * 1000
print(distance_in_m)
```

This works with all common arithmetic operations

- Addition: `my_array + 10` 
- Subtraction: `my_array - 10`
- Multiplication: `my_array * 10`
- Division: `my_array / 10`

### Exercise: Concentration conversion

In an experiment you have measured the concentration a solution in units of $\mu\mathrm{M}$ (micromolar) but you need to work with them in millimolar. Use the cell below to convert the concentrations. 

```{pyodide}
#| exercise: convert_conc
#| check: true

if np.isclose(conc_mM, conc_uM/1000).all():
    feedback = {'correct': True, "message": "The conversion is correct."}
else:
    feedback = {"correct": False, "message": "That's not correct. Try again."}

feedback
```

```{pyodide}
#| exercise: convert_conc

import numpy as np

conc_uM = np.array([137.03, 205.1, 56.4, 732.2, 1563.3])

conc_mM = ______

print("Concentrations in millimolar: ", conc_mM)
```


## Data collections: DataFrames

Lists lets us avoid having a huge amount of variables, arrays extend that to also let 
us make calculations across the entire dataset - however we are still left with only an implicit connection between different arrays. 

We can go one step further and work with `DataFrames` which are kind of an extension of an excel-document in Python. 

```{python}
import pandas as pd

df = pd.DataFrame({'wavelengths': [400, 401], 'adsorptions': [2.451, 2.532]})
print(df)
```

Now the full dataset is contained in one variable (here called `df`) - this makes working with a dataset much easier. A `DataFrame` can also be indexed, for example we extract the `wavelengths` like so 

```{python}
df['wavelengths']
```

So with a `DataFrame` indexing uses the name of the row or column rather than the numeric index we've seen for lists and arrays. 

### Exercise: Calculating cell sizes 

The code below creates a dataset using a `DataFrame` with cell types and the upper and lower limits of their radii.

```{pyodide}
import pandas as pd

cell_data = pd.DataFrame({
    'cell_type': ["Mycoplasma", "Typical bacterium", "Yeast cell", "Red blood cell",
    "Lymphocyte", "Typical animal cell", "Typical plant cell", "Human egg cell (oocyte)",
    "Neuron (cell body)"], 
'radius_lower_um': [0.2, 1, 5, 7, 8, 10, 20, 120, 10], 
'radius_upper_um': [0.3, 2, 7, 8, 10, 20, 100, 140, 100]}).set_index('cell_type')

print(cell_data)
```

We would like to calculate the volume of these cells, assuming they are spherical 

$$
V(r) = \frac{4}{3}\pi r^3
$$

#### Calculate the volume of a myocoplasma

We will start by making the calculation as if Python was almost just a normal calculator. 

Put in the correct lower limit of the radius and calculate the volume of the cell in the interactive cell below. 

Here you are not expected to make use the `cell_data` variable.

```{pyodide}
#| exercise: cell_volume_1
#| check: true

feedback = {"correct": False, "message": "..."}
pi = 3.1415

if mycoplasma_radius != 0.2:
    feedback['correct'] = False
    feedback['message'] = "That's not the correct radius."
elif mycoplasma_volume != 4/3 * pi * 0.2**3:
    feedback['correct'] = False
    feedback['message'] = "That's not the correct volume."
else:
    feedback['correct'] = True
    feedback['message'] = "Thats correct!"

feedback 
```


```{pyodide}
#| exercise: cell_volume_1
pi = 3.1415
mycoplasma_radius = ______ # Write the correct radius
mycoplasma_volume = ______ # Calculate the volume

print("The volume is", mycoplasma_volume)
```

#### Calculate the volume of mycoplasma - but smarter.

```{pyodide}
#| exercise: cell_volume_2
#| setup: true

import pandas as pd

cell_data = pd.DataFrame({
    'cell_type': ["Mycoplasma", "Typical bacterium", "Yeast cell", "Red blood cell",
    "Lymphocyte", "Typical animal cell", "Typical plant cell", "Human egg cell (oocyte)",
    "Neuron (cell body)"], 
'radius_lower_um': [0.2, 1, 5, 7, 8, 10, 20, 120, 10], 
'radius_upper_um': [0.3, 2, 7, 8, 10, 20, 100, 140, 100]}).set_index('cell_type')
```

It's kind of silly to create the `cell_data`-table (or rather `DataFrame`) and then not use it. 
So now we want to extract the lower limit of the radius of the mycoplasma cell from the `DataFrame` rather than writing it manually. 

To do so we need to use *indexing* to extract the entry we are interested in.


```{pyodide}
#| exercise: cell_volume_2
pi = 3.1415
mycoplasma_radius = cell_data['radius_lower_um'][______]
mycoplasma_volume = ______

print("The volume is", mycoplasma_volume)
```

#### Calculate the volume of all the cells 

Each column in `cell_data` is actually an array, so we can easily calculate volumes of 
every cell at once. 

```{pyodide}
#| exercise: cell_volume_3
#| setup: true

import pandas as pd

cell_data = pd.DataFrame({
    'cell_type': ["Mycoplasma", "Typical bacterium", "Yeast cell", "Red blood cell",
    "Lymphocyte", "Typical animal cell", "Typical plant cell", "Human egg cell (oocyte)",
    "Neuron (cell body)"], 
'radius_lower_um': [0.2, 1, 5, 7, 8, 10, 20, 120, 10], 
'radius_upper_um': [0.3, 2, 7, 8, 10, 20, 100, 140, 100]}).set_index('cell_type')
```

```{pyodide}
#| exercise: cell_volume_3
pi = 3.1415

# This extracts the array of lower limit cell sizes. 
cell_volumes = ______ * cell_data['radius_lower_um']**3

print(cell_volumes)
```

[^1]:
    In many programming languages, counting starts at 0 instead of 1. This comes from how computers store lists in memory.

    You can think of a list as starting at some location in memory, and each new element being a fixed step away.  
    The index then tells the computer how many steps to move from the start:

    - index `0` → move 0 steps → first element  
    - index `1` → move 1 step → second element  
    - index `2` → move 2 steps → third element  

    This makes it simple and efficient for the computer to find elements. Most modern programming languages have kept this convention.