---
title: Working with data
format: 
  live-html:
    toc: true
    number-sections: true
    css: ../styling/styles.css
    theme:
      light: cosmo
      dark: [darkly, ../styling/theme-dark.scss]
    respect-user-color-scheme: true

pyodide:
  packages:
    - pandas
    - openpyxl
---

In this note we will explore some common operations when working with datasets. 
We will be using the dataset presented in this [paper](https://www.sciencedirect.com/science/article/pii/S2352340919302264?utm_source=chatgpt.com) on "the absorption characteristics of extracted phytoplankton pigments".

```{python}
import pandas as pd

pigments = pd.read_csv('../datasets/curated_abs_dataset.csv')
display(pigments)
```

## Plotting 

One of the best ways to explore a dataset is to plot it, below one column of the dataset is 
plotted

```{python}
#| fig-align: center
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

# Plotting
ax.plot(pigments['wavelength_nm'], 
      pigments['chlorophyll-a'], 
      label='Chlorophyll-a') # <1>

# These are settings to make the plot look nice
ax.set_xlabel('Wavelength [nm]') # <2>
ax.set_ylabel('Adsorption')

ax.legend() # <3> 

# This tell Python to display the plot.
plt.show() # <4>
```
1. Here we plot by picking the x-axis as the wavelength from the dataset and the y-axis as measurements of chlorophyll-a
2. Setting the x-axis name. 
3. Show the label in a little box, helps if we plot multiple curves in the same figure.
4. Show the plot.

### Exercise: Plotting

Use the cell below to plot some of the other columns of the dataset.

Try to plot several columns at the same time.

```{pyodide}
#| echo: false

import matplotlib.pyplot as plt
import pandas as pd

url = 'https://raw.githubusercontent.com/au-mbg/imol/refs/heads/main/course_notes/datasets/curated_abs_dataset.csv'

pigments = pd.read_csv(url)
```

```{pyodide}
fig, ax = plt.subplots()

# Your code for plotting here

plt.show()
```

### Exercise: Interpreting plots

Chlorophyll a is the main photosynthetic pigment, while chlorophyll b is an accessory pigment found in green algae and land plants. Use the plotted spectra to explain why having both pigments could be useful. 

## Data manipulations

We often need to transform parts of our data - e.g. 

- Converting units
- Calculating derived properties
- Normalizing 

Our dataset has the wavelength in nanometers, perhaps we would like to work with meters instead 

```{python}
pigments['wavelength_m'] = pigments['wavelength_nm'] * 10**(-9)
```

This is an example of an **element-wise operation** - every element of `pigments['wavelength_nm']`
is multiplied by `10**(-9)`. 

### Exercise: Converting to photon energy

A more interesting unit conversion for this dataset would be to work with photon energy in eV, 
which can be computed with the formula 

$$
E = \frac{1240}{\lambda}
$$
Where $E$ is the photon energy and $\lambda$ is the wavelength.

Use the cell below to make this conversion

```{pyodide}
#| exercise: convert_exercise
#| setup: true

import matplotlib.pyplot as plt
import pandas as pd

url = 'https://raw.githubusercontent.com/au-mbg/imol/refs/heads/main/course_notes/datasets/curated_abs_dataset.csv'

pigments = pd.read_csv(url)
```

```{pyodide}
#| exercise: convert_exercise
# Replace the blank line below with your code to make the conversion
_______

# Make a plot with the x-axis as photon energy 
fig, ax = plt.subplots()

_______ 

plt.show()
```

### Exercise: Mixture of pigments

```{pyodide}
#| exercise: mixture_exercise
#| setup: true  

import matplotlib.pyplot as plt
import pandas as pd

url = 'https://raw.githubusercontent.com/au-mbg/imol/refs/heads/main/course_notes/datasets/curated_abs_dataset.csv'

pigments = pd.read_csv(url)
```

We can approximate the absorbance of a mixture by using the equation 

$$
A_{\mathrm{mixture}}(\lambda) = c_1 \cdot A_1(\lambda) + c_2 \cdot A_2(\lambda)
$$
Where $A$ are absorbances of each component of the mixture and $c_i$ are proportions of each component. Use this to calculate the absorbance of a mixture of 70% `chlorophyll-a` and 30% `chlorophyll-b` 

```{pyodide}
#| exercise: mixture_exercise
# Calculate the mixture
c1 = ______
c2 = ______
A_mixture = _______

# Plot the mixture absorbance
fig, ax = plt.subplots()

x_data = pigments['wavelength_nm']
ax.plot(x_data, pigments['chlorophyll-a'], label='c-a')
ax.plot(x_data, pigments['chlorophyll-b'], label='c-b')
______

plt.show()
```


