project:
  type: website

website:
  title: "Introduktion til Livets Molekyler"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: python_intro/index.qmd
        text: Python Intro
        icon: code-slash
      - href: markdown_intro/index.qmd
        text: Markdown Intro
        icon: markdown
      - href: quiz_example/quiz.qmd
        text: Quiz Example
        icon: question

  sidebar: 
    - id: python-intro-sidebar
      style: "docked"
      contents:
        - section: "Python Intro"
          contents:
            - python_intro/python_intro.qmd
            - python_intro/python_data.qmd
    - id: markdown-intro-sidebar
      style: "docked"
      contents:
        - section: "Markdown Intro"
          contents:
            - markdown_intro/index.qmd

format:
  html:
    toc: true
    number-sections: true
    css: styling/styles.css
    include-after-body: styling/markdown-playground.html
    theme:
      light: cosmo
      dark: [darkly, styling/theme-dark.scss]
    respect-user-color-scheme: true

