project:
  type: book
  output-dir: _site/downloads/

book:
  title: "IMoL Python course notes"
  author: "Ditlev E. Brodersen & Mads-Peter V. Christiansen"
  chapters:
    - index.qmd
    - python_intro/toe1/intro.qmd
    - python_intro/toe3/variables_functions.qmd
    - python_intro/toe3/extra.qmd
    - python_intro/toe4/lab_exercise_1.qmd
    - python_intro/toe4/extra.qmd
    - python_intro/toe5/data_types.qmd
    - python_intro/toe5/extra.qmd
    - python_intro/toe7/working_with_data.qmd
    - python_intro/toe7/extra.qmd
    - python_intro/toe9/lab_exercise_2.qmd

format:
  typst:
    pandoc:
      filters:
        - path: filters/static-pyodide.lua
          at: pre-ast
    toc: true
    number-sections: true
    number-depth: 2
    toc-depth: 2
    margin:
      left: 2cm
      right: 2cm
      top: 2.5cm
      bottom: 2.5cm
